<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXBP4ul\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXBP4ul/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXBP4ul.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXXBP4ul\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXXBP4ul\App_KernelDevDebugContainer([
    'container.build_hash' => 'XXBP4ul',
    'container.build_id' => '8629c4e6',
    'container.build_time' => 1610361780,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXBP4ul');
